name: CI/CD for Python Server and Next.js

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.15.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version


      - name: Create .env.local file in ctrlc
        run: |
          echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" >> ./ctrlc/.env.local
          echo "NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}" >> ./ctrlc/.env.local
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> ./ctrlc/.env.local
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> ./ctrlc/.env.local
          echo "NEXT_PUBLIC_STRIPE_PUBLIC_KEY=${{ secrets.NEXT_PUBLIC_STRIPE_PUBLIC_KEY }}" >> ./ctrlc/.env.local
          echo "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}" >> ./ctrlc/.env.local
          echo "STRIPE_WEBHOOK_SECRET=${{ secrets.STRIPE_WEBHOOK_SECRET }}" >> ./ctrlc/.env.local


      - name: Create .env file for Docker Compose
        run: |
          echo "STRIPE_RK=${{ secrets.STRIPE_RK }}" >> .env

      - name: Build and run containers with Docker Compose
        run: |
          docker-compose -f docker-compose.yml --env-file .env up --build -d

      - name: Wait for containers to be ready
        run: sleep 10

      - name: Stop Docker containers
        run: docker-compose down
